### ISSUE TITLE
Normalization for the feature

### ISSUE THREAD

**Issue by Nathan-zh** [brandontrabucco/design-baselines#14]
Hi Brandon, 

Just a new question in this repo. For this line,
https://github.com/brandontrabucco/design-baselines/blob/785dbcfa58107bfcc426257a1c2e69d7f71c3c27/design_baselines/coms_cleaned/__init__.py#L323
When I trace back, from top to bottom, when we set `normalize_xs=True`
```
if normalize_xs:
        task.map_normalize_x()
x = task.x
initial_x = tf.gather(x, indices, axis=0)
xt = initial_x
solution = xt
# for here 'solution' should be a normalized feature
# should this be  'task.denormalize_x(solution)' instead of 'solution'?
# I guess the 'predict' function is designed for original feature
score = task.predict(solution)
```
Maybe I have some misunderstanding. Please let me know. Thanks!

Nathan

**Comment by brandontrabucco** [comment]
Hi [Nathan-zh](https://github.com/Nathan-zh),

Thanks for your interest in the code!  The `task.predict` internally tracks if the task features are normalized, and will automatically denormalize them when evaluating the designs at this line of code:

https://github.com/brandontrabucco/design-bench/blob/27ed0c3d1c28acb43084fac1b317fc7268cd7c9a/design_bench/oracles/oracle_builder.py#L495

-Brandon

**Comment by Nathan-zh** [comment]
That's great. I skim your codes and find the flag `is_normalized_x`. Thanks so much!
